
version: "3.7"

networks:
  proxy:
    external: true
  nextcloud-net:
    name: nextcloud-net
    external: false

services:
  db:
    container_name: nextcloud-db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    networks:
      - nextcloud-net

  main:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/nextcloud/html:/var/www/html
    environment:
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    links:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=letsencrypt
      - traefik.http.routers.nextcloud.entrypoints=https
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)
    networks:
      - proxy
      - nextcloud-net
    depends_on:
      - db

