---
kind: pipeline
type: exec
name: Deployment-Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: Deploy
  environment:
    ROOT_PATH:
      from_secret: root_path
  commands:
  # - cp deploy.py $ROOT_PATH/deploy.py
  - cd $ROOT_PATH && sudo ./deploy.py
  when:
    branch:
    - main
    event:
    - push
