---
kind: pipeline
type: exec
name: Deployment-Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: Deploy
  commands:
  - ./deploy.py
  environment:
    ROOT_PATH:
      from_secret: root_path
  when:
    branch:
    - main
    event:
    - push
