
version: "3.7"

networks:
  proxy:  # Used to detect and route to apps & stacks

services:
  # Traefik Reverse Proxy + LetsEncrypt auto-https
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ${GLOBAL_STORAGE}/ssl/acme.json:/acme.json
    labels:
      # HTTP
      - traefik.http.routers.traefik-http.service=api@internal
      - traefik.http.routers.traefik-http.entrypoints=http
      - traefik.http.routers.traefik-http.rule=Host(`${DOMAIN_TRAEFIK}`)
      # HTTPS
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`${DOMAIN_TRAEFIK}`)
    networks:
      - proxy

  # Portainer for management & deployments
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GLOBAL_STORAGE}/portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.rule=Host(`${DOMAIN_PORTAINER}`)
    networks:
      - proxy
