global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

pilot:
    token: ${PILOT_TOKEN}

providers:
  docker:
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: acme.json
      httpChallenge:
        entryPoint: http

log:
  filePath: ${GLOBAL_STORAGE}/traefik/traefik.log

accessLog:
  filePath: ${GLOBAL_STORAGE}/traefik/access.log
