
version: "3.7"

services:
  vault:
    image: vaultwarden/server:latest
    container_name: service-vault
    restart: unless-stopped
    volumes:
      - ${GLOBAL_STORAGE}/bitwarden:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vault.tls=true
      - traefik.http.routers.vault.tls.certresolver=letsencrypt
      - traefik.http.routers.vault.entrypoints=https
      - traefik.http.routers.vault.rule=Host(`${DOMAIN}`)
    environment:
      - SIGNUPS_ALLOWED=${SIGNUPS}
    networks:
      - proxy

networks:
  proxy:
    external: true
