
version: "3.7"

services:
  code:
    container_name: service-code
    image: lscr.io/linuxserver/code-server
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${GLOBAL_STORAGE}/code/data:/data
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.code.tls=true
      - traefik.http.routers.code.tls.certresolver=letsencrypt
      - traefik.http.routers.code.entrypoints=https
      - traefik.http.routers.code.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.code.loadbalancer.server.port=8443

networks:
  proxy:
    external: true
