
version: '3.3'

services:
  server:
    image: 'bitwardenrs/server:latest'
    container_name: bitwarden
    restart: always
    volumes:
      - '/home/ap/global_storage/dr1:/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ward-ui.tls=true"
      - "traefik.http.routers.ward-ui.entrypoints=https"
      - "traefik.http.routers.ward-ui.rule=Host(`ward.hs.alexpdr.com`)"
      - "traefik.http.routers.ward.tls.certresolver=letsencrypt"
    environment:
      - "SIGNUPS_DOMAINS_WHITELIST=@alexpdr.com"
    networks:
      - "proxy"

networks:
  proxy:
    external: true