version: '3.3'
services:
  server:
    image: 'bitwardenrs/server:latest'
    container_name: bitwarden
    restart: always
    volumes:
      - '/home/ap/global_storage/dr1:/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ward-ui.tls=true"
      - "traefik.http.routers.ward-ui.entrypoints=https"
      - "traefik.http.routers.ward-ui.rule=Host(`ward.hs.alexpdr.com`)"
      - "traefik.http.routers.ward-ui.service=ward-ui"
      - "traefik.http.services.ward-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.ward-socket.rule=Host(`ward.hs.alexpdr.com`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.ward-socket.service=ward-socket"
      - "traefik.http.services.ward-socket.loadbalancer.server.port=301"
    networks:
      - "proxy"

networks:
  proxy:
    external: true