version: '3.3'
services:
  server:
    image: 'bitwardenrs/server:latest'
    container_name: bitwarden
    restart: always
    volumes:
      - '/home/ap/global_storage/dr1:/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ward.tls=true"
      - "traefik.http.routers.ward.entrypoints=https"
      - "traefik.http.routers.ward.rule=Host(`ward.hs.alexpdr.com`)"
    networks:
      - "proxy"

networks:
  proxy:
    external: true