
version: '3.7'

services:
  whoami:
    container_name: "whoami"
    image: "traefik/whoami:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.rule=Host(`whoami.hs.alexpdr.com`)"
    networks:
      - "proxy"

networks:
  proxy:
    external: true
