
version: "3.7"

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - /home/ap/global_storage/minio:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.rule=Host(`minio.hs.alexpdr.com`)"
    networks:
      - "proxy"

networks:
  proxy:
    external: true
